[package]
name = "ziptree"
version = "0.1.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"
description = "Tarjan's zip tree implemented in Rust"
categories = ["data-structures", "algorithms"]
license = "MIT"
license-file = "LICENSE"

[dependencies]
rand = "^0.6"
